Added code for radio map estimation with autonomous UAVs.
uiano/SpectrumSurveyingMLSP pull request #1
Opened 2020-09-21 12:52 UTC by raju-stha

2020-09-22 20:51 UTC, fachu000 commented
Thanks Raju. There seems to be no README file or any other file explaining how to run the simulations, right? Then, the user will not be able to run this...

2020-09-24 07:36 UTC, raju-stha commented
Yes, it is important to have READme file. Okay, I will provide basic guidelines for execution of the files.

2020-09-24 10:03 UTC, fachu000 commented
> Yes, it is important to have READme file. Okay, I will provide basic guidelines for execution of the files.

Sounds good. Thanks.

2020-09-25 15:26 UTC, fachu000 requested changes
Nice job! just a small change and I will merge.

2020-09-25 15:26 UTC, fachu000 commented on README.md
> +........
This seems incomplete. I suggest you also write that they may send you an email if they have trouble running the code.

2020-09-27 11:07 UTC, merged